class ImportStatus:
    RAW_EXTRACTED = "RAW_EXTRACTED"
    VALIDATED = "VALIDATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    IMPORTED = "IMPORTED"
    DUPLICATE_SKIPPED = "DUPLICATE_SKIPPED"
    MAPPED = "MAPPED"
    VALIDATED_AND_MAPPED = "VALIDATED_AND_MAPPED"
